addappid(1804010)
addappid(1804011, 2343876080, "9e2dda820fdffc53cc3820a3315777e79e7ce3789f88843cea754bca4b09a897")


-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: Labyrinth Of The Demon King
